String sort implemented.
js-tasks-ru/js-20210921_sequence pull request #2
Opened 2021-09-29 13:39 UTC by hyperfield

2021-09-29 13:41 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-09-30 13:25 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +let engAlphabetOrder = ["A", "a", "B", "b", "C", "c", "D", "d", "E", "e", "F", "f", "G",
пожалуйста, дайте ответ на вопрос: как данная функция будет расширяться, если строки у нас будут еще на 3х дополнительных языках? К примеру на японском, итальянском и корейском?

2021-09-30 13:25 UTC, dosandk requested changes
необходимо дать ответ на вопрос

2021-09-30 14:03 UTC, hyperfield commented on 02-javascript-data-types/1-sort-strings/index.js
> +let engAlphabetOrder = ["A", "a", "B", "b", "C", "c", "D", "d", "E", "e", "F", "f", "G",
Будут расширяться путём добавления новых массивов с алфавитами.

2021-09-30 14:55 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-10-01 15:56 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +let engAlphabetOrder = ["A", "a", "B", "b", "C", "c", "D", "d", "E", "e", "F", "f", "G",
При таком подходе, наш файл разрастется от количества массивов разных языков. Более того, добавление каждого нового языка будет сопряжено с трудностями по добавлению алфавита, посмотрите, например как выглядит китайский алфавит. Но к счастью разработчики JS уже позаботились о том чтобы нам не пришлось вручную добавлять эти алфавиты, `localeCompare` принимает аргумент локалей 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare
в соответствии с которыми решает как сортировать строки

2021-10-01 15:57 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> -
good 👍

2021-10-01 15:57 UTC, dosandk requested changes
решение `sortStrings` следует поправить, использовать метод `localeCompare`

2021-10-02 11:34 UTC, hyperfield commented
Не видится возможным использовать `localeCompare` так как он не сортирует строки с верхним регистром перед строками с нижним регистром для кириллицы. Например,

```
function sortStrings(arr, param = "asc") {
 return arr.slice().sort((a, b) => a.localeCompare(b), 'ru-u-kf-upper');
}
```
sortStrings(['абрикос', 'Абрикос', 'яблоко', 'Яблоко', 'ёжик', 'Ёжик'], 'asc'); // ['абрикос', 'Абрикос', 'ёжик', 'Ёжик', 'яблоко', 'Яблоко']

2021-10-02 12:58 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-10-04 19:42 UTC, merged